os: linux
dist: xenial
language: node_js
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      node_js: 14
      before_install:
        - npm i -g codecov
      script:
        - npm run verify
        - npm run test:ci
      after_success:
        - codecov
    - stage: deploy
      node_js: 14
      install: true
      before_script:
        - chmod +x publish-website.sh
      script:
        - ./publish-website.sh
notifications:
  email:
    on_success: never
    on_failure: always
